### ISSUE TITLE
Feature request: export ref_azimuth and ref_elev with ATL03

### ISSUE THREAD

**Issue by jonm3D** [ICESat2-SlideRule/sliderule-python#103]
These two fields from ATL03 can be used to calculate the underwater return refraction correction, and are vital for conducting ICESat-2 bathymetry research. Having the ability to pull these with the atl03sp() would be fantastic!

**Comment by jpswinski** [comment]
@jonm3D thanks for letting us know!  We would love to be able to support bathymetry research, and will try to get this into the next release.  The main difficultly will be in figuring out a way to include these parameters on request while still leaving them out when they are not needed.  This is something we need to solve for other parameters as well, so it is something we need to solve sooner than later.  I'll track the progress in this issue.

**Comment by jpswinski** [comment]
@jonm3D I am closing this out as complete - but if you have any issues, please reopen this issue or open a new one.
