### ISSUE TITLE
Provide default upper limits on request size

### ISSUE THREAD

**Issue by jpswinski** [ICESat2-SlideRule/sliderule-python#12]
The atl06p api should have a max_allowed_granules AND a maximum area that can be overridden but is there to alert the user that they have made a very large request - it will force them to override the limit explicitly.

This also brings up the question of absolute limits on request size, but that should be deferred until we have authentication.  Once we have authenticated users we can apply user-based limits, with a small limit for anonymous users.

**Comment by jpswinski** [comment]
2ce0c97

Added check against maximum allowed resources to process in one request.  Currently it is set to 300 and can be overridden by a function call icesat2.set_max_resources(). 

Couple additional comments:
* Opted to have it configured globally instead of per function since managing it per function would require a lot of duplicate code and would also further grow the number of parameters for each function
* Opted to NOT include an area calculation and check - the number of granules being processed strongly correlates to the area request and the code needed to do the area calculation could be error prone and would require importing Python packages that are currently not needed.
* If an area check becomes necessary (the granule check is not sufficient), then we can always add it later.

**Comment by dshean** [comment]
Seems like a good solution.  Thinking about the difference in granule count expected for a small area near 88 S vs granule count near equator for an equivalent area.  Granule count is more important.
