### ISSUE TITLE
Additional filelds in the ATL06 structure

### ISSUE THREAD

**Issue by SmithB** [ICESat2-SlideRule/sliderule-python#13]
It would be great to have some additional fields in the ATL06 output:
n_fit_photons: The number of photons remaining for each segment after the iterations are finished
rms_misfit: the rms misfit between the selected photons for each segment and the segment
h_sigma: the propagated error in the segment center height (using rms_misfit as the estimated per-photon error)
w_surface_window_final: the height of the window after the iterations are finished.

Of these, h_sigma is probably the hardest, and the lowest priority.
Thanks!

**Comment by jpswinski** [comment]
ICESat2-SlideRule/sliderule-icesat2@a8dc586bfec234879f3084488d9f0760e82e7b4d

Adds n_fit_photons and w_surface_window_final.
Also created a compact option that will only return the lat, lon, height, and time.

**Comment by jpswinski** [comment]
I've noticed that the w_surface_window_final value is being returned as all zeroes.  I will be continuing to work this issue along with adding the other requested fields.

**Comment by jpswinski** [comment]
The issue with w_surface_window_final is fixed.  Moving on to the others.

**Comment by jpswinski** [comment]
rms_misfit has been added to atl06:  ICESat2-SlideRule/sliderule-icesat2@41170186cd1d5647d46b5887b5cf6857b6a5434d

**Comment by jpswinski** [comment]
h_sigma has been added to atl06: ICESat2-SlideRule/sliderule-icesat2@833a3bd
