### ISSUE TITLE
Residual issues with icesat2.toregion()

### ISSUE THREAD

**Issue by dshean** [ICESat2-SlideRule/sliderule-python#18]
`icesat2.atl06p` runs without issue for grand_mesa_poly2.geojson after https://github.com/ICESat2-SlideRule/sliderule-python/pull/17.  But it fails for the simpler grand_mesa_poly.geojson.  The latter was manually created in QGIS, and incremental vertices were added after defining the initial polygon, so could be an ordering issue.

I had to rename from .geojson to .txt to attach in Github issue:
[grand_mesa_poly.txt](https://github.com/ICESat2-SlideRule/sliderule-python/files/6275822/grand_mesa_poly.txt)
[grand_mesa_poly2.txt](https://github.com/ICESat2-SlideRule/sliderule-python/files/6275824/grand_mesa_poly2.txt)

**Comment by dshean** [comment]
OK, it's an ordering issue.  Using current implementation:
```
poly_fn = 'grand_mesa_poly.geojson'
region = icesat2.toregion(poly_fn)
region

[{'lon': -108.31168256553767, 'lat': 39.13757646212944},
 {'lon': -108.17287000970857, 'lat': 39.15920066396116},
 {'lon': -108.04939480098754, 'lat': 39.139504663354245},
 {'lon': -107.78724142490994, 'lat': 39.195630349659986},
 {'lon': -107.72839858755752, 'lat': 39.01510930230633},
 {'lon': -107.98560510494981, 'lat': 38.9439912011017},
 {'lon': -108.07460164311031, 'lat': 38.8475137825863},
 {'lon': -108.20772968780051, 'lat': 38.8232055291981},
 {'lon': -108.2878686387796, 'lat': 38.89051431295789},
 {'lon': -108.34115668325224, 'lat': 39.03758987613325},
 {'lon': -108.31168256553767, 'lat': 39.13757646212944}]
```

Using GeoPandas/Shapely:

```
pregion = gpd.read_file(poly_fn)
region = []
for i in list(pregion_geom.exterior.coords):
    region.append({"lon":i[0], "lat":i[1]})
region

[{'lon': -108.31168256553767, 'lat': 39.13757646212944},
 {'lon': -108.34115668325224, 'lat': 39.03758987613325},
 {'lon': -108.2878686387796, 'lat': 38.89051431295789},
 {'lon': -108.20772968780051, 'lat': 38.8232055291981},
 {'lon': -108.07460164311031, 'lat': 38.8475137825863},
 {'lon': -107.98560510494981, 'lat': 38.9439912011017},
 {'lon': -107.72839858755752, 'lat': 39.01510930230633},
 {'lon': -107.78724142490994, 'lat': 39.195630349659986},
 {'lon': -108.04939480098754, 'lat': 39.139504663354245},
 {'lon': -108.17287000970857, 'lat': 39.15920066396116},
 {'lon': -108.31168256553767, 'lat': 39.13757646212944}]
```

**Comment by dshean** [comment]
I've been working to clean up and improve the Grand Mesa example notebook.  I pushed to new branch on my fork: https://github.com/dshean/sliderule-python/tree/gm_update.  Can open PR once we've had a chance to touch base.

The rendered notebook is here: https://nbviewer.jupyter.org/github/dshean/sliderule-python/blob/gm_update/examples/grand_mesa_demo.ipynb.  Filesize is small (282 KB), so I did not clear output.

I updated environment.yml with geopandas.  I think we should include as dependency, as it simplifies the Point within Polygon step and some of the plotting, and we can drop cartopy.  I'd say swapping the above code using geopandas `gpd.read_file()` for the existing `icesat2.toregion()` function might simplify geojson handling (and handle other vector polygon formats users may want to use to define region, like ESRI Shapefiles)

**Comment by jpswinski** [comment]
The demo looks really good!  The elevation plots are a big improvement over what was there.  

On a side note, it looks like it may have been branched from the `main` branch instead of the `development` branch because it is still using the old h5 api instead of the h5p api.  When you put in the PR, it may take some finagling to get it all merged in, but it is something I can easily take care of.

**Comment by jpswinski** [comment]
The GeoPandas/Shapely doesn't seem to work with the original Sierra geojson files you sent me.  I think I'll need to touch base with you offline so you can help me understand the different formats and what we should standardize on.

**Comment by jpswinski** [comment]
Per team tagup:
* At the least need to support single polygon in geojson format
* For multipolygons, either issue warning log message and take first one, or handle all of them
* Do not need to handle polygons with holes in them
* Recommended approach is to use geopandas ( → fionna → gdal → geos) to read shape files and put into format recognized by CMR

**Comment by jpswinski** [comment]
Also need to use the Randal Glacier Inventory (RGI) set of shapefiles as a good test set for the different user inputs we will need to support: https://www.glims.org/RGI/

**Comment by jpswinski** [comment]
6d866cb - support for simplifying shapes in the toregion function
