### ISSUE TITLE
Suppress "unable to process" messages

### ISSUE THREAD

**Issue by SmithB** [ICESat2-SlideRule/sliderule-python#26]
CMR is fairly sloppy about finding RGTs that cross a region.  As a result, ATL06p requests tend to report a lot of messages of the form:
unable to process resource ATL03_20190111063212_02110206_003_01.h5: no elements
unable to process resource ATL03_20190209050825_06530206_003_01.h5: no elements
If verbose is set to False, these probably don't need to be reported.

**Comment by jpswinski** [comment]
The way to do this right now is to configure the Python logger level for CRITICAL.  I have a snippet below that will do it.   But I think the long term solution is to handle all logging configuration as a function of the verbose setting and/or an optional log level that gets passed to the icesat2.init(..) function.

```python
# Configure Logging
icesat2_logger = logging.getLogger("sliderule.icesat2")
icesat2_logger.setLevel(logging.CRITICAL)

# Create Console Output
ch = logging.StreamHandler()
ch.setLevel(logging.CRITICAL)
icesat2_logger.addHandler(ch)
```

**Comment by jpswinski** [comment]
7dd9f6a

The icesat2.init verbose parameter will not automatically configure the logging level to be either INFO (verbose=True) or CRITICAL (verbose=False).

The calling script can always override the settings and set the logging level to whichever they chose (either by the method described in the comment above OR the simpler `logging.basicConfig(level=logging.<level>)`
