### ISSUE TITLE
Specify a single rgt/cycle to be processed with atl06p

### ISSUE THREAD

**Issue by SmithB** [ICESat2-SlideRule/sliderule-python#27]
There may already be a way to do this, but it seems like ATL06p can only process an entire region.  It would be nice to be able to specify a single rgt and/or cycle to be processed.

**Comment by jpswinski** [comment]
@SmithB This is now possible with the icepyx api.  See: http://icesat2sliderule.org/rtd/user_guide/icepyx.html

I'm still planning to add native support for this to the icesat2.py module; but until then the icepyx api gives access to all the features that icepyx provides in its region structure.

**Comment by jpswinski** [comment]
Native support for this has now been added.  The following three parameters are accepted in the request dictionary:
`rgt`: <reference ground track>
`cycle`: <cycle number>
`region': <region number>

The way it works behind the scenes is that it uses these values to create a filename regular expression that is passed to CMR when requesting granules.
