### ISSUE TITLE
Is there a way to identify which beam is strong or weak with the sliderule output?

### ISSUE THREAD

**Issue by mansi278** [ICESat2-SlideRule/sliderule-python#33]
Is there a way to identify which beam is strong or weak with the sliderule output?

**Comment by jpswinski** [comment]
Yes, in the current version (1.0.7), you can use the `spot` field returned by the `icesat2.atl06p` function to determine if the beam is strong or weak.  If the spot == 1, 3, or 5, then it is a strong beam.  If the spot == 2, 4, or 6, then it is a weak beam.

In the next release (1.1.0) we are going to make it a little easier by adding a ground track identifier (GT1L, GT1R, GT2l, GT2R, GT3L, and GT3R) to the returned elevations, and also some helper constants in the `icesat2` module.  So when the next release comes out (hopefully mid next week), you should be able to do things like:

```python
    new_df = df[df["gt"] == icesat2.GT1L]
```
and

```python
    new_df = df[df["spot"].isin(icesat2.WEAK_SPOTS)]
```

**Comment by jpswinski** [comment]
V1.1.0 is released - closing this issue
