### ISSUE TITLE
MyBinder fails to build

### ISSUE THREAD

**Issue by jpswinski** [ICESat2-SlideRule/sliderule-python#34]
The link in the RTD documentation (on the installation page) to run the SlideRule Python client via mybinder does not work.

The link is: https://mybinder.org/v2/gh/ICESat2-SlideRule/sliderule-python/main

![image](https://user-images.githubusercontent.com/54070345/129614221-4616ddaa-b377-4ca0-95a4-82e926772303.png)

**Comment by jpswinski** [comment]
I've removed the link from the documentation for now until this can be resolved.

**Comment by jpswinski** [comment]
Same as above for the Pangeo binder link.

**Comment by jpswinski** [comment]
The mybinder links in the readme now work.

**Comment by scottyhq** [comment]
builds succeed after #50 so i think this can be closed, but running sliderule via mybinder.org still has some issues (#48)
