### ISSUE TITLE
Problem running the api_widgets_demo

### ISSUE THREAD

**Issue by slhowardESR** [ICESat2-SlideRule/sliderule-python#59]
After installing the SlideRule Python client, I had trouble running the api_widgets_demo.

I installed using  Alternate Method 2: Development install from repository

   git clone https://github.com/ICESat2-SlideRule/sliderule-python.git
   cd sliderule-python
   conda env create -f environment.yml

When I run the notebook, it gives me an error in the "create output plots" section:

![error_api_demo1](https://user-images.githubusercontent.com/5480396/136730572-e809a09a-0f6b-40cd-8a3b-335660a17da2.PNG)

It looks like it grabbed the data and mostly plotted it.  I tried this for different areas/projections.

And it looks like there is another issue:
 
![filesaver](https://user-images.githubusercontent.com/5480396/136731030-18731b24-32dd-4c76-b9f5-40c327565e45.PNG)

I assume it is a problem with the installation?   But I wanted to pass on the info, in case it is useful.

The single_track_demo and grand_mesa_demo worked perfectly.

**Comment by jpswinski** [comment]
@slhowardESR Are you still having this issue?  Sorry it's taken me so long to get to this.

I initially was not able to run the widgets example in my local jupyter notebook, but after updating my base environment (`conda update -n base --all`) and then creating a new sliderule environment (`conda env create -f environment.yml`), everything ran fine.  Could you give that a try and let me know if that works for you?

**Comment by slhowardESR** [comment]
Hi @jpswinski, sorry for the delay.  I was busy with other work and the holidays.   I have updated everything.   The api_widgets_demo now works all the way through if I keep it on the land setting and global projection (the saving/reading worked as well).  

However, I tried to run with with different projections (North and South) and get this error now:
![Capture1](https://user-images.githubusercontent.com/5480396/150179435-9688e985-3643-4a7c-9dc0-1fb013f9d9a9.PNG)
![Capture2](https://user-images.githubusercontent.com/5480396/150179444-769c421e-3325-4e06-98b0-e7d7179b9d4b.PNG)

this was part was working well previously. 

Let me know if you want me to test something again.  I should be more responsive now.

thanks!

**Comment by jpswinski** [comment]
@slhowardESR thanks for taking a look at this again and running through the demo.  I am glad that the original issue has been resolved, but the current issue has me stumped.  @tsutterley can you take a look and see why using a northern or southern projection would cause this error to occur?

**Comment by tsutterley** [comment]
Hey @slhowardESR I just put in a PR to address this issue.  There were changes in ipyleaflet that required some changes on our side (we use additional polar maps than what is provided by ipyleaflet).  Let me know if you still have problems!

**Comment by jpswinski** [comment]
@slhowardESR The latest version of the code just release (v1.3.3) has the PR @tsutterley submitted that fixes this issue.  I ran the API widgets demo on the released version and verified that I could do a northern and a southern projection.  If you continue to have any issues, please let me know or reopen this issue.
