### ISSUE TITLE
Standardized response considerations

### ISSUE THREAD

**Issue by jpswinski** [ICESat2-SlideRule/sliderule-python#72]
From Scott: 
> This is not something currently in SlideRule, but we could consider ways in which the results of SlideRule can be made Cloud-friendly and utilize some emerging standards:  Specifically I'm thinking about how sliderule results are saved. We typically want to work with a GeoDataFrame, but what about saving that to share 'downstream' with other software or colleagues. The example notebooks suggest saving to HDF5. What if there were an option to stage on S3 for some limited period of time as Zarr or Parquet with accompanying STAC metadata https://github.com/stac-extensions/pointcloud?

**Comment by jameshgrn** [comment]
Adding a suggestion for feather files instead of parquet for short term fast io. Also natively read by geopandas
