### ISSUE TITLE
Problem when saving NetCDF files

### ISSUE THREAD

**Issue by slhowardESR** [ICESat2-SlideRule/sliderule-python#75]
I have been having problems trying to save a file to netCDF.

Saving to h5 files works fine.  

However, when I try to save same dataframe in a netcdf file I get this error:

![dist_err](https://user-images.githubusercontent.com/5480396/154313073-4f2f95fa-13ac-4b97-b1bf-974b9c726b05.PNG)

I can just delete distance and it works:

![dist_works](https://user-images.githubusercontent.com/5480396/154313407-735575c5-f7ca-475a-8a4d-3a9ec46027ea.PNG)

Anyway - I can make things work, but wanted to pass this along.

**Comment by jpswinski** [comment]
@slhowardESR Thanks for catching this bug and reporting it.  I see the same thing in my setup.  It looks like a field was added to the atl06 record returned from the server, but we didn't update the io module code to reflect it.

I have a fix in my local branch, and the next release (hopefully late next week), will have the fix in it.  I'll let you know as soon as it is released so you can do an update.

**Comment by jpswinski** [comment]
Ran the following code snippet and verified it worked:

```Python
from sliderule import icesat2, ipysliderule, io
SRwidgets = ipysliderule.widgets()
parmsyp = {}
version = icesat2.get_version()
parmsyp['version'] = version['icesat2']['version']
parmsyp['commit'] = version['icesat2']['commit']
io.to_file(atl06_sr, SRwidgets.file, format=SRwidgets.format, driver='pytables', parameters=parmsyp, verbose=True)
```

**Comment by jpswinski** [comment]
@slhowardESR Please update your sliderule client and things should work now.  

```bash
cd sliderule-python
git pull
python setup.py install
```
